### ISSUE TITLE
TextInput requires a "css" property

### ISSUE THREAD

**Issue by jclem** [primer/react#1391] opened 2021-08-24 16:39 UTC
**Describe the bug**

The `<TextInput />` component requires an undocumented `css` property with the type `unknown`.

<img width="948" alt="CleanShot 2021-08-24 at 12 38 36@2x" src="https://user-images.githubusercontent.com/412282/130655845-ec2ffe3d-650c-4179-8371-0c7f1fe52d5c.png">

**Comment by colebemis** [comment] 2021-08-25 16:19
Closing this as a duplicate of https://github.com/primer/react/issues/1163

**Closed by colebemis** 2021-08-25 16:19 UTC
