### ISSUE TITLE
ConfirmationDialog with confirmButtonVariant=danger lack focus state

### ISSUE THREAD

**Issue by mattcosta7** [primer/react#3194] opened 2023-04-19 19:00 UTC
### Description

Originally reported elsewhere by @dylanatsmith 

And confirmed in the primer docs - where no focus styles are found on the "OK" button in this example

![Screenshot 2023-04-19 at 2 57 02 PM](https://user-images.githubusercontent.com/8616962/233173839-d5f008b0-8f63-4eff-8a0d-48424aafac2f.png)

It seems like focus styles apply for the default confirm button, but not danger (haven't tried other types)

### Steps to reproduce

ConfirmDIalog with a confirmButtonType= danger

Use this on the docs site - 

```
<State default={false}>
  {([isOpen, setIsOpen]) => {
    const openDialog = React.useCallback(() => setIsOpen(true), [setIsOpen])
    const closeDialog = React.useCallback(() => setIsOpen(false), [setIsOpen])
    return (
      <>
        <Button onClick={openDialog}>Open</Button>
        {isOpen && (
          <ConfirmationDialog       confirmButtonType="danger" title="Confirm action?" onClose={closeDialog}>
            Are you sure you want to confirm this action?
          </ConfirmationDialog>
        )}
      </>
    )
  }}
</State>
```

### Version

latest

**Comment by langermank** [comment] 2023-04-19 19:10
@mattcosta7 is this a duplicate of https://github.com/primer/react/issues/3062?

**Comment by iansan5653** [comment] 2023-04-19 19:10
Duplicate of https://github.com/primer/react/issues/3062

(I recently also opened a duplicate of this issue)

**Closed as not planned by iansan5653** 2023-04-19 19:10 UTC
Labels: bug, react
