### ISSUE TITLE
Dialog V2 - Entire dialog is re-rendering when contents change

### ISSUE THREAD

**Issue by dusave** [primer/react#3442] opened 2023-06-21 23:50 UTC
### Description

https://github.com/primer/react/assets/2447456/0f2c0b96-eb03-462d-8c2f-3e879acc9a52

As you can see in the video, I've used the React Developer Tools to trace down the reason that keyboard focus was resetting back to the close button of the dialog. The reason for this appears to be due to the dialog completely re-rendering itself and its contents, but not returning focus to the element that had it previously.

### Steps to reproduce

1. Go to https://github-5c92e0b3ed-35265154.drafts.github.io/storybook/?path=/story/filter--filter-example and click on the filter button
2. Add a filter from the menu in the lower left
3. Use your keyboard to select the filter provider (first action menu) to open the menu
4. Use your arrow keys to select a filter provider and hit enter

Expected: Focus returns to the filter provider action menu anchor button
Actual: Focus goes _backwards_ to the Dialog close button

### Version

v35.25.0

### Browser

Chrome

**Comment by lesliecdubs** [comment] 2023-06-22 22:41
According to https://github.com/github/planning-tracking/issues/2025#issuecomment-1602834693 this is a higher priority bug as it breaks accessibility and keyboard focus in the new Filter shared component: https://github-5c92e0b3ed-35265154.drafts.github.io/storybook/?path=%2Fstory%2Ffilter--filter-example

**Comment by lesliecdubs** [comment] 2023-06-29 23:04
Apologies for not commenting on this sooner when it was triaged earlier this week! 

This issue remained in the [PRC Inbox](https://github.com/orgs/github/projects/4503/views/10) because this week was reserved for [Passion Week](https://github.com/github/core-ux/discussions/115). We will triage again on Monday July 3 and either assign a team member to drive this work, or comment back to discuss mitigation.

**Comment by lesliecdubs** [comment] 2023-07-03 21:43
@keithamus as you're on FR this week, would you be willing to take a look into this and see if it's something you have enough context to address? Feel free to reach out to the PRC crew as needed.

**Comment by keithamus** [comment] 2023-07-04 14:22
The `Dialog` is stable and doesn't re-render with each change.

What is happening is the implementation of `AdvancedFilterItem` re-renders its contents when changing the first dropdown, including removing said dropdown. As the dropdown no longer exists on the page, the element loses focus and `Dialog` pulls focus back into the dialog. To reproduce this effect, move focus to the second or third dropdowns (which don't rerender) and select one of those. By interacting with the second or third dropdowns, one can see that they're not re-rendered and focus remains stable. A video:


https://github.com/primer/react/assets/118266/b0f9f82f-614d-4ce3-9589-ddb566735be5



In addition if you use the browsers built in dev tools (rather than React) you can break on subtree modifications and node removal for all of the constituent parts of the dialog. You'll find that the break points are not triggered for the dialog header, footer, nor does breaking on node removal of the dialog body. Here's a demonstration video showing how the first dropdown re-renders all of the contents:

https://github.com/primer/react/assets/118266/d98020f1-2618-40b7-9bc5-9b5c840a36c9




My recommendation is for the first dropdown to be refactored in order for it to not re-render itself every time an option is selected.

I'm closing this because this is not a bug within Dialog, rather `AdvancedFilterItem`.

**Closed by keithamus** 2023-07-04 14:22 UTC
Labels: bug, react, component: dialog
