### ISSUE TITLE
Dropdown component is not keyboard navigable

### ISSUE THREAD

**Issue by mperrotti** [primer/react#1383] opened 2021-08-18 14:43 UTC
## Describe the bug
The Dropdown can be opened using the keyboard, but the items inside cannot be selected using the arrow keys.

## To Reproduce
1. Go to https://primer.style/react/Dropdown or any page with a dropdown
2. Focus the Dropdown button
3. Open the menu using "Space" or "Enter"
4. Try to navigate the Dropdown menu items using your keyboard's arrow keys

## Expected behavior
I expect to be able to navigate the menu items using my keyboard's arrow keys. I'd also expect the dropdown menu to open when I focus the button and press the "up" or "down" arrow key.

## Screenshots
https://share.getcloudapp.com/z8urxleX

**Comment by mperrotti** [comment] 2021-08-18 17:42
I just discovered the DropdownMenu component, which _is_ keyboard accessible: https://primer.style/react/DropdownMenu

However, it's not listed in the components in the sidebar navigation. I discovered it by reading [this comment](https://github.com/github/primer/discussions/247#discussioncomment-1062817)

@vdepizzol - I've got a few questions about this:
- Is DropdownMenu intentionally hidden in the docs? If so, why?
- When building/designing new stuff, how do we know whether to use Dropdown or DropdownMenu?

**Comment by vdepizzol** [comment] 2021-08-18 22:19
@mperrotti I think `DropdownMenu` hasn't been included in the navigation list mainly due to its `alpha` state. But looking at it now, I think it's making it hard for discovering it (the component page already has a status indicator anyway).

`DropdownMenu` is part of the recent overlay effort, alongside some other components:

- https://primer.style/react/SelectPanel
- https://primer.style/react/ActionMenu
- https://primer.style/react/anchoredPosition
- https://primer.style/react/AnchoredOverlay
- https://primer.style/react/Overlay

I think the decision should come based on how comfortable the team is with using an `alpha` component, whether the component is working for them, and whether they're willing to adapt to breaking changes. The [documentation around feature lifecycle](https://github.com/primer/design/pull/174/files) should help with the decision-making process.

@smockle @dgreif what are your thoughts on making these components visible in the nav?

**Comment by smockle** [comment] 2021-08-19 13:50
From @vdepizzol in https://github.com/primer/react/issues/1383#issuecomment-901467150:
> I think `DropdownMenu` hasn't been included in the navigation list mainly due to its `alpha` state.

Yup. 👍 We’d planned to unhide the docs for new layered components once they were exported in `index.ts`. In the case of `DropdownMenu`, its types still aren’t being exported there: https://github.com/primer/react/blob/b31f08533e9fd41ebc5dc0e109d09facd975287c/src/index.ts#L84-L86

From @vdepizzol in https://github.com/primer/react/issues/1383#issuecomment-901467150:
> @smockle @dgreif what are your thoughts on making these components visible in the nav?

It makes sense to me 👍 Hiding the docs was intended to avoid confusion; instead, it’s creating confusion. `SelectMenu` vs `SelectPanel` is another example: [github/primer#247 (comment)](https://github.com/github/primer/discussions/247#discussioncomment-1062817).

**Comment by siddharthkp** [comment] 2022-03-15 11:26
We can close this issue now that [Dropdown](https://primer.style/react/deprecated/Dropdown) has been deprecated and replaced with [ActionMenu](https://primer.style/react/ActionMenu) which has keyboard navigation :)

**Closed by siddharthkp** 2022-03-15 11:26 UTC
Labels: accessibility
