### ISSUE TITLE
SelectMenu has required css property

### ISSUE THREAD

**Issue by pavelkeyzik** [primer/react#1380] opened 2021-08-17 12:21 UTC
## Describe the bug
I tried to use `<SelectMenu>` from [this example](https://primer.style/react/SelectMenu#right-aligned-modal) and get an error message that css property is missing

## To Reproduce
1. Copy [this](https://primer.style/react/SelectMenu#right-aligned-modal) code from docs
2. Error should appear

## Expected behavior
There is no error message. I think that css property should not be required

## Screenshots
<img width="967" alt="image" src="https://user-images.githubusercontent.com/17102399/129723899-216efaae-7820-4388-b6c8-e92d4eacc344.png">

## Additional context
@primer/components v28.3.1
TypeScript v4.3.5

**Comment by colebemis** [comment] 2021-08-17 16:47
Hi, @pavelkeyzik. That's likely related to this issue: https://github.com/primer/react/issues/1163

We're working on a fix. In the meantime, let me know if @dmarcey's [workaround](https://github.com/primer/react/issues/1163#issuecomment-839148254) works for you.

**Comment by pavelkeyzik** [comment] 2021-08-17 20:10
Thanks, @colebemis! It works well 👍

**Comment by colebemis** [comment] 2021-09-16 19:27
Closing this as a duplicate of #1163

**Closed by colebemis** 2021-09-16 19:27 UTC
