### ISSUE TITLE
Slot causing problems with suspense in react 18

### ISSUE THREAD

**Issue by alexus37** [primer/react#2688] opened 2022-12-13 18:19 UTC
### Description

Wrapping suspense around a PageLayout header causes the following error.

![SCR-20221213-h1j](https://user-images.githubusercontent.com/7422767/207413630-4701e924-d7f3-4fb7-9fe7-65cabe1c4ee5.png)

### Steps to reproduce

Before (working):

```js
     <PageLayout.Header>
         <Suspense fallback={<IssueHeaderLoading />}>
            <Header />
         </Suspense>
     </PageLayout.Header>
```

After (failing)

```js
      <Suspense fallback={<IssueHeaderLoading />}>
        <PageLayout.Header>
            <Header />              
        </PageLayout.Header>
      </Suspense>
```

### Version

v35.15.1

**Comment by joshblack** [comment] 2022-12-13 21:52
Hi there @alexus37! 👋 

Thanks for taking the time to make this issue 🙏 I'm trying to reproduce on my end but am having some trouble 🤔 I tried to mirror what you shared in one of stories:

```tsx
export const SuspenseDemo = () => {
  return (
    <PageLayout>
      <React.Suspense fallback={<p>Loading...</p>}>
        <PageLayout.Header divider="line">header</PageLayout.Header>
      </React.Suspense>
      <PageLayout.Pane position="start" divider="line">
        pane
      </PageLayout.Pane>
      <PageLayout.Content>content</PageLayout.Content>
    </PageLayout>
  )
}
```

With this example, I suspend using devtools and it seems okay (although the layout seems to be incorrect). Could you share any more details about how this component is being rendered/called that leads to the error you shared?

**Comment by joshblack** [comment] 2023-01-17 21:55
Hey @alexus37! 👋 Just wanted to reach out again to see if you had any tips for how to reproduce the issue. Trying to find a good standalone example to test against / include in the project 👀

**Comment by joshblack** [comment] 2023-01-25 17:18
Follow-up to this, it's seems to be related to this change in React 18: https://github.com/reactwg/react-18/discussions/31, specifically that any layout effects that run as part of mounting a suspended tree will also have their cleanup function called. This is what causes the loop between Slots and Slot as the child component unregisters itself which forces an update on Slots.

Loom for more information: https://www.loom.com/share/0c899184970c469b99a5614c1a4bde48

**Comment by joshblack** [comment] 2023-08-28 15:53
This should be addressed due to moving away from the `createSlots` implementation and towards `useSlots` which is using `React.Children` under the hood instead of layout effects 👍 

Going to close this out for now, feel free to comment/re-open if this is still a problem!

**Closed by joshblack** 2023-08-28 15:53 UTC
Labels: bug, react
