### ISSUE TITLE
SSR `FormControl` htmlFor attribute mismatch

### ISSUE THREAD

**Issue by GlebIrovich** [primer/react#3554] opened 2023-07-24 09:48 UTC
### Description

We are trying to [enable](https://github.com/issues/assigned) the SSR for our react app, however in dev mode I see a lot of errors related to the `htmlFor` mismatch between server and client.

![ htmlFor attribute mismatch stack trace screenshot](https://github.com/primer/react/assets/33176414/5e87df81-cabd-46bd-bf7c-5b6026e15068)

Following the suggestions in this [thread](https://github.slack.com/archives/C01L618AEP9/p1689860062470749), I manually added ids to every form control component. 

This resulted in a new issue: color mode mismatch:

```
react-dom.development.js:86 Warning: Prop `data-color-mode` did not match. Server: "dark" Client: "auto"
    at div
    at O (http://127.0.0.1/webpack/vendors-node_modules_primer_octicons-react_dist_index_esm_js-node_modules_primer_react_lib-es-fb382e-f86ce5f82dfb.js:16846:19291)
    at BaseStyles (http://127.0.0.1/webpack/vendors-node_modules_primer_octicons-react_dist_index_esm_js-node_modules_primer_react_lib-es-fb382e-f86ce5f82dfb.js:11952:5)
    at OptionalBaseStyles (http://127.0.0.1/webpack/ui_packages_react-core_deferred-registry_ts-ui_packages_react-core_AppContextProvider_tsx-ui_-36d03f-a38db5a39ee6.js:381:31)
    at Fe (http://127.0.0.1/webpack/vendors-node_modules_primer_octicons-react_dist_index_esm_js-node_modules_primer_react_lib-es-fb382e-f86ce5f82dfb.js:16846:16840)
    at ThemeProvider (http://127.0.0.1/webpack/vendors-node_modules_primer_octicons-react_dist_index_esm_js-node_modules_primer_react_lib-es-fb382e-f86ce5f82dfb.js:12149:3)
    at IntlProvider (http://127.0.0.1/webpack/ui_packages_react-core_deferred-registry_ts-ui_packages_react-core_AppContextProvider_tsx-ui_-36d03f-a38db5a39ee6.js:205:25)
    at RenderPhaseProvider (http://127.0.0.1/webpack/ui_packages_react-core_deferred-registry_ts-ui_packages_react-core_AppContextProvider_tsx-ui_-36d03f-a38db5a39ee6.js:855:32)
    at $704cf1d3b684cc5c$export$9f8ac96af4b1b2ae (http://127.0.0.1/webpack/vendors-node_modules_primer_octicons-react_dist_index_esm_js-node_modules_primer_react_lib-es-fb382e-f86ce5f82dfb.js:12686:64)
    at BaseProviders (http://127.0.0.1/webpack/ui_packages_react-core_deferred-registry_ts-ui_packages_react-core_AppContextProvider_tsx-ui_-36d03f-a38db5a39ee6.js:399:30)
    at Entry (http://127.0.0.1/webpack/ui_packages_react-core_Entry_tsx-ed5a5cf46f72.js:1204:18)
```

I am not sure if those two are related.

### Steps to reproduce

1. checkout to https://github.com/github/github/pull/281165
2. enable `repos_forms_ssr` FF
3. start codespaces and go to `/new`
4. make sure that you see SSR icon in the toolbar, reload if needed 
5. check console

### Version

v35.26.0

### Browser

Chrome

**Comment by lesliecdubs** [comment] 2023-07-24 15:57
Thanks for reporting! @joshblack is going to take a stab at reproducing and then we'll go from there.

**Comment by joshblack** [comment] 2023-07-25 18:05
Hey there! 👋 I opened up: https://github.com/primer/react/pull/3561 which should help for the FormControl id mismatch issue. It seemed to be due to an issue in an upstream dependency when in StrictMode 👀 

For the theme mismatch issue, could you share more info about how to re-create it? On my end, I opened up a codespace for the linked branch and did the following:

- Visited `/new`
- Added the following features as query params: `/new?_features=react_repo_create_page,repos_forms_ssr`

When the page renders, I see the error mentioned for ids:

```
Prop `htmlFor` did not match. Server: "react-aria-1" Client: "react-aria-2"
```

But am unsure how to re-create the `data-color-mode` mismatch. Any more information you can share here would be super helpful!

**Comment by GlebIrovich** [comment] 2023-07-26 08:42
thanks @joshblack!

I am not sure if there is a simple way to reproduce the theme mismatch issue. In my case I added ids to all form controls manually (which resolved the problem with `htmlFor`) and the theme problem popped up.

I committed my changes,  so you can try going to the same page on this [commit](https://github.com/github/github/pull/281165/commits/cd929ff3494a7a390aebdb42c83fa68a9fe5bffa)

**Comment by GlebIrovich** [comment] 2023-07-28 09:07
@joshblack did it work for you?

**Comment by joshblack** [comment] 2023-07-28 15:33
Yup! That did it. Thanks so much @GlebIrovich for the help, really appreciate it. Will look into the theme side of things now 👍

**Comment by joshblack** [comment] 2023-07-31 17:21
Small update 👇 

Reaching out over in: https://github.slack.com/archives/CMZ4DC9BL/p1690824050891049 on Slack to see what may be happening during SSR with `ThemeProvider` upstream 👀

**Comment by GlebIrovich** [comment] 2023-08-08 07:33
Hey folks, I was able to repro the same issue with the theme provider on a newly generated react app 😢 
Are there any updates on that?

**Comment by joshblack** [comment] 2023-08-14 16:33
Hi @GlebIrovich! 👋 So sorry for the delay. I believe that in a new react app in dotcom we run into the problem above due to the cookie behavior described in that Slack thread. In a standalone React app, this problem should not occur if `SSRProvider` is used. Are you seeing this issue in a standalone React app? If so, could you share some steps to reproduce?

**Comment by GlebIrovich** [comment] 2023-08-15 08:54
Hey, I think it's taken care by the web systems team not and tracked here
https://github.com/github/web-systems/issues/1628

**Comment by GlebIrovich** [comment] 2023-08-15 08:55
are there any updates on the `FormControl`? Thanks!

**Comment by joshblack** [comment] 2023-08-15 20:21
Sounds good @GlebIrovich! And yes, thankfully the original issue from an upstream dependency has been merged and included in the next release! Link to PR: https://github.com/primer/react/pull/3561

**Comment by joshblack** [comment] 2023-12-05 17:52
Going to close this issue out as I believe it has been addressed! Please comment/re-open if that is not the case.

**Closed by joshblack** 2023-12-05 17:52 UTC
Labels: bug, react
