### ISSUE TITLE
`@primer/react` is incompatible with `next` 12.2.5 / `create-next-app`

### ISSUE THREAD

**Issue by manuanish** [primer/react#2271] opened 2022-08-25 07:22 UTC
**Describe the bug**
Next.js causes an error when attempting to import components from `@primer/react`

**To Reproduce**
1. Create a blank Next.js project using 
```bash
yarn create next-app primer-bug
```
2. Install `@primer/react`.
```bash
yarn add @primer/react styled-components
```
3. Edit the index.js to import a component; e.g
```jsx
import { Button } from "@primer/react";

export default function Home() {
  return (
    <Button></Button>
  )
}
```
4. Start the dev server using `yarn dev`
5. Next.js gives us the following error:

```
error - Error [ERR_REQUIRE_ESM]: require() of ES Module primer-bug/node_modules/@github/combobox-nav/dist/index.js from primer-bug/node_modules/@primer/react/lib/drafts/hooks/useCombobox.js not supported.
Instead change the require of index.js in primer-bug/node_modules/@primer/react/lib/drafts/hooks/useCombobox.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (primer-bug/node_modules/@primer/react/lib/drafts/hooks/useCombobox.js:8:43)
    at Object.<anonymous> (primer-bug/node_modules/@primer/react/lib/drafts/InlineAutocomplete/_AutocompleteSuggestions.js:16:20)
    at Object.<anonymous> (primer-bug/node_modules/@primer/react/lib/drafts/InlineAutocomplete/InlineAutocomplete.js:22:55)
    at Object.<anonymous> (primer-bug/node_modules/@primer/react/lib/drafts/InlineAutocomplete/index.js:8:50)
    at Object.<anonymous> (primer-bug/node_modules/@primer/react/lib/FormControl/FormControl.js:28:50)
    at Object.<anonymous> (primer-bug/node_modules/@primer/react/lib/FormControl/index.js:13:43)
    at Object.<anonymous> (primer-bug/node_modules/@primer/react/lib/index.js:669:43)
    at Object.@primer/react (primer-bug/.next/server/pages/index.js:32:18)
    at __webpack_require__ (primer-bug/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/index.js:7:71)
    at Object../pages/index.js (primer-bug/.next/server/pages/index.js:22:1)
    at __webpack_require__ (primer-bug/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (primer-bug/.next/server/pages/index.js:52:39)
    at primer-bug/.next/server/pages/index.js:53:28
    at Object.<anonymous> (primer-bug/.next/server/pages/index.js:56:3)
    at Object.requirePage (primer-bug/node_modules/next/dist/server/require.js:58:12)
    at primer-bug/node_modules/next/dist/server/load-components.js:56:50
    at async Promise.all (index 2)
    at async Object.loadComponents (primer-bug/node_modules/next/dist/server/load-components.js:53:49)
    at async DevServer.findPageComponents (primer-bug/node_modules/next/dist/server/next-server.js:451:36) {
  code: 'ERR_REQUIRE_ESM',
  page: '/'
}
```

**Comment by siddharthkp** [comment] 2022-08-25 10:10
Thank you for reporting, would you consider this a duplicate of https://github.com/primer/react/issues/2245?

**Comment by manuanish** [comment] 2022-08-25 10:22
> Thank you for reporting, would you consider this a duplicate of #2245?

Yep! Sounds good.

**Closed** 2022-08-25 10:22 UTC
Labels: react
